
### Metagenomic Microbiome Combination Analysis Workflow ###

configfile: "config/config.yaml"

### Define samples wildcard for input and output ###

print("Importing Python modules...")

import pandas as pd
import os
import fileinput
import glob

# Load metadata

print("Loading metadata and creating wildcards...")

metadata = config['metadata_file']

sample_df = pd.read_table(metadata, header=0)

# Create sample paths wildcard
sample_df['Path'] = None

for row in range(len(sample_df)):
    sample = sample_df.loc[row,'Sample_ID']
    run = sample_df.loc[row,'Run']
    path = str().join(run+'/'+sample)
    sample_df.loc[row,'Path'] = path

# Define wildcards and their constraints for workflow

SAMPLE_IDS = list(sample_df['Sample_ID'])
SAMPLE_PATHS = list(sample_df['Path'])
ALL_RUNS = list(sample_df.Run.unique())

wildcard_constraints:
  SAMPLE_PATHS = ".*\/.*",
  SAMPLE_IDS = "[^\/]+",
  ALL_RUNS = "[^\/]+"

### Provide path for report file ###

report: "rules/report/workflow.rst"

### Target rule ###

rule all:
  input:
    "results/database_creation.done",
    "results/QC_reports/assembly_stat_reports/stats_report.tsv",
    "results/QC_reports/humrm_qc_reports/stats_report.tsv",
    "results/CAT/cat_plot_list.txt",
    "results/BLAST/blast_plot_list.txt",
    "results/Kraken2/kraken2_plot_list.txt",
    "results/Assigner_comparison/output_list.txt",

### Remaining rules for workflow ###

# Optional subworkflow to build databases
include: "rules/db_creation.smk"

# 1. filter on size and quality
include: "rules/fastp.smk"

# 2. human filtering
include: "rules/removing_human_seq.smk"

# 3. read assembly
include: "rules/metaflye.smk"

# 4. taxonomically assign with kraken2
include: "rules/kraken2.smk"

# 5. Taxonomic assignment and annotation with CAT
include: "rules/contig_annotation_tool.smk"

# 6. Alignment to NCBI NT with BLAST
include: "rules/blast.smk"

# 7. Comparison of taxonomy assigner results
include: "rules/taxonomy_assigner_comparison.smk"

# 8. Running phylophlan
#include: "rules/phylophlan.smk"
