
### Metagenomic Microbiome Combination Analysis Workflow ###

configfile: "config/config.yaml"

### Define samples wildcard for input and output ###

print("Importing Python modules...")

import pandas as pd
import os
import fileinput
import glob

# Load metadata

print("Loading metadata and creating wildcards...")

metadata = config['metadata_file']

sample_df = pd.read_table(metadata, header=0)

# Create sample paths wildcard
sample_df['Path'] = None

for row in range(len(sample_df)):
    sample = sample_df.loc[row,'Sample_ID']
    run = sample_df.loc[row,'Run']
    path = str().join(run+'/'+sample)
    sample_df.loc[row,'Path'] = path

# Define wildcards and their constraints for workflow

IDS = list(sample_df['Sample_ID'])
PATHS = list(sample_df['Path'])
RUNS = list(sample_df.Run.unique())

wildcard_constraints:
  PATHS = ".*\/.*",
  IDS = "[^\/]+",
  RUNS = "[^\/]+"

### Optional analyses ###

optional_outputs = list()

# Database creation option
if config['include_db_creation'] == True:
    optional_outputs.extend(["results/database_creation.done"])

# Taxonomic assigner options
if config['include_cat'] == True:
    optional_outputs.extend(["results/cat/cat_plot_list.txt"])
if config['include_kraken2'] == True:
    optional_outputs.extend(["results/kraken2/kraken2_plot_list.txt"])
if config['include_blast'] == True:
    optional_outputs.extend(["results/blast/blast_plot_list.txt"])
if config['include_phylophlan'] == True:
    optional_outputs.extend([""])
if config['include_sourmash'] == True:
    optional_outputs.extend([""])

# Assigner comparison options
if config['include_comparison'] == True & config['include_kraken2'] == True & config['include_blast'] == True & config['include_cat'] == True:
    optional_outputs.extend(["results/assigner_comparison/output_list.txt"])
elif config['include_comparison'] == True & config['include_kraken2'] == True & config['include_blast'] == True:
    optional_outputs.extend(["results/assigner_comparison/output_list.txt"])
elif config['include_comparison'] == True & config['include_cat'] == True & config['include_kraken2'] == True:
    optional_outputs.extend([""])
elif config['include_comparison'] == True & config['include_blast'] == True & config['include_cat'] == True:
    optional_outputs.extend([""])

# Resistance gene identification option
if config['include_rgi'] == True:
    optional_outputs.extend([""])

### Provide path for report file ###

report: "rules/report/workflow.rst"

### Target rule ###

rule all:
  input:
    "results/qc_reports/sample_post_qc_report.tsv",
    "results/qc_reports/assembly_stat_report.tsv",
    "results/qc_reports/humrm_qc_report.tsv",
    optional_outputs = optional_outputs,

### Remaining rules for workflow ###

## Optional subworkflow to build databases

if config['include_db_creation'] == True:
    
    include: "rules/db_creation.smk"

    print("Optional subworkflow to build databases will be run")
else:
    print("Optional subworkflow to build databases will not be included")

## 1. Filter on size and quality
include: "rules/fastp.smk"

## 2. Host sequence filtering
include: "rules/removing_human_seq.smk"

## 3. Read assembly with metaflye
include: "rules/metaflye.smk"

## 4: Taxonomic assignment

# Kraken2
if config['include_kraken2'] == True:
    
    include: "rules/taxdump.smk"
    
    include: "rules/kraken2.smk"

    print("Kraken2 will be used to perform taxonomic assignment")
else:
    print("Kraken2 will not be included")

# CAT
if config['include_cat'] == True:
    
    include: "rules/contig_annotation_tool.smk"

    print("CAT will be used to perform taxonomic assignment")
else:
    print("CAT will not be included")

# BLAST
if config['include_blast'] == True:
    
    include: "rules/taxdump.smk"

    include: "rules/blast.smk"

    print("BLAST will be used to perform taxonomic assignment")
else:
    print("BLAST will not be included")

# Sourmash
if config['include_sourmash'] == True:

    include: "rules/sourmash.smk"

    print("Sourmash will be used to perform taxonomic assignment")
else:
    print("Sourmash will not be included")

# PhyloPhlAn
if config['include_phylophlan'] == True:
    
    include: "rules/phylophlan.smk"

    print("PhyloPhlAn will be used for phylogenetic analysis")
else:
    print("PhyloPhlAn will not be included")

## 5. Optional comparison of taxonomy assigner results

# Compare all assigners
if config['include_comparison'] == True & config['include_kraken2'] == True & config['include_blast'] == True & config['include_cat'] == True:
    
    include: "rules/taxonomy_assigner_comparison.smk"

    print("Optional taxonomic assigner comparison of all assigners will be performed")
elif config['include_comparison'] == True & config['include_kraken2'] == True & config['include_blast'] == True:
    
    include: "rules/taxonomy_assigner_comparison.smk"

    print("Optional taxonomic assigner comparison of Kraken2 and BLAST will be performed")
elif config['include_comparison'] == True & config['include_cat'] == True & config['include_kraken2'] == True:

    include: ""

    print("Optional taxonomic assigner comparison of CAT and Kraken2 will be performed")
elif config['include_comparison'] == True & config['include_blast'] == True & config['include_cat'] == True:

    include: ""

    print("Optional taxonomic assigner comparison of BLAST and CAT will be performed")
else:
    print("Taxonomic assigner comparison will not be performed")

## 6. Search for antimicrobial genes

if config['include_rgi'] == True:

    include: "rules/card_rgi.smk"

    print("Resistance gene identification will be performed")
else:
    print("CARD RGI will not be included")