###  Config file for preliminary skin microbiome metagenomic snakemake workflow ###

conda_envs: "environment.yml"

metadata_file: "config/seq_test_metadata.tsv"

### Analysis options ###

# option for database creation

# option for cat

# option for kraken2

# option for blast

# option for phylophlan

# option for ARG identification

# option for comparison - requires at least 2 assigners on

### Database locations ###
# Place your reference databases in these locations or edit to specify the location

filtering_reference: "workflow/rules/Database_Creation_Workflow/results/human_reference/GCF_000001405.39_GRCh38.p13_genomic.fna"
#"resources/databases/human_reference/GCF_000001405.39_GRCh38.p13_genomic.fna"

kraken_db: "resources/databases/kraken2_std_database"

cat_db: "workflow/rules/Database_Creation_Workflow/results/CAT/CAT_database*"
#"resources/databases/CAT_database"
cat_taxonomy: "workflow/rules/Database_Creation_Workflow/results/CAT/CAT_taxonomy*"
#"resources/databases/CAT_taxonomy"

blast_db: "workflow/rules/Database_Creation_Workflow/results/NCBI_blast_database/nt"
#"resources/databases/NCBI_blast_database/nt"

taxdump: "workflow/rules/Database_Creation_Workflow/results/taxdump"
#"resources/databases/taxdump"

### Parameters ###

# For fastp
qualified_quality_phred: "10" # quality value that a base is qualified - Default 15 means phred quality >=Q15 is qualified.
unqualified_percent_limit: "40" # how many percents of bases are allowed to be unqualified (0~100) - Default 40 means 40%
average_qual: "0" # if one read's average quality score <avg_qual, then this read/pair is discarded - Default 0 means no requirement (int [=0])
min_length: "100" # minimum length requirement
front_trim: "0" # number of bases to trim off the front of the read
tail_trim: "0" # number of bases to trim off the tail of the read

# For metaflye
read_type: "--nano-raw"
# --nano-corr: is ONT reads that were corrected with other methods (<3% error)
# --nano-raw: ONT regular reads, pre-Guppy5 (<20% error)
minimum_overlap: "1000"
# minimum overlap length for two reads to be considered overlapping, Typical value is 3k-10k (and down to 1k for datasets with shorter read length)

# For kraken2
kraken_confidence: "0.1" #specify a threshold score in the [0,1] interval;
# classifier then will adjust labels up the tree until the label's score (described below) meets or exceeds that threshold

# For BLAST
BLAST_min_perc_ident: "70"
BLAST_min_evalue: "1e-5"
BLAST_max_target_seqs: "5"

# For LCA assignment
MLCA_bitscore: "500"
MLCA_identity: "70"
MCLA_coverage: "60"
MLCA_majority: "70"
MLCA_hits: "1"
